# Generated by Django 4.2.7 on 2025-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shortened_url', models.CharField(max_length=10, unique=True)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['original_url'], name='url_shorten_origina_9080ea_idx'),
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['shortened_url'], name='url_shorten_shorten_0635c8_idx'),
        ),
    ]
